name: Deploy CRUD S3 Service

on:
  push:
    branches: [dev, test, main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ----------------------
      # SET ENV
      # ----------------------
      - name: Set environment
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "test" ]]; then
            echo "ENV=test" >> $GITHUB_ENV
          else
            echo "ENV=dev" >> $GITHUB_ENV
          fi

      # ----------------------
      # AWS AUTH
      # ----------------------
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # ----------------------
      # LOAD CONFIG (SERVICE NAME + BUCKET)
      # ----------------------
      - name: Load config
        run: |
          SERVICE_NAME=$(jq -r ".service.name" config/env-config.json)
          BUCKET=$(jq -r ".environments.${ENV}.s3_bucket" config/env-config.json)

          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
          echo "BUCKET=$BUCKET" >> $GITHUB_ENV

      # ----------------------
      # BUILD LAMBDA
      # ----------------------
      - name: Build package
        run: |
          mkdir -p build

          cd lambdas/
          zip -r ../build/${SERVICE_NAME}-db-artifact.zip . > /dev/null
          cd ..

      # ----------------------
      # UPLOAD TO S3
      # ----------------------
      - name: Upload Lambda
        run: |
          aws s3 cp \
            build/${SERVICE_NAME}-db-artifact.zip \
            s3://$BUCKET/${ENV}-jsvm-service/${SERVICE_NAME}-db.zip

      # ----------------------
      # DEPLOY CFN
      # ----------------------
      - name: Deploy Infra
        run: |
          aws cloudformation deploy \
            --template-file infra/service-infra-cft.yaml \
            --stack-name crud-${ENV} \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides BucketName=$BUCKET